#I'll start by creating a table of songs that the symphony mentions they'll be performing. Because some composers are not very creative when it comes to name choices, I'll assign each song an ID number, which will be the primary key.

CREATE TABLE SONGS (
	SONG_ID int PRIMARY KEY NOT NULL,
	TITLE varchar(100) NOT NULL,
	COMPOSER varchar(100) NOT NULL,
	CONDUCTOR varchar(100) NOT NULL,	
	CONCERT varchar(200) NOT NULL
	);
 
#Now adding the data

INSERT INTO SONGS
VALUES 
	(1, 'Banner', 'Jessie Montgomery', 'Xian Zhang', 'Yefim Bronfman Plays Rachmaninoff'),
	(2, 'Appalachian Spring Suite', 'Aaron Copland', 'Xian Zhang', 'Yefim Bronfman Plays Rachmaninoff'),
	(3, 'Piano Concerto No. 3', 'Sergei Rachmaninoff', 'Xian Zhang', 'Yefim Bronfman Plays Rachmaninoff'),
	(4, 'Northern Star', 'Dorothy Chang', 'Xian Zhang', 'Xian Zhang Conducts Brahms'),
	(5, 'Burlesque for Piano and Orchestra', 'Richard Strauss', 'Xian Zhang', 'Xian Zhang Conducts Brahms'),
	(6, 'Symphony No. 4', 'Johannes Brahms', 'Xian Zhang', 'Xian Zhang Conducts Brahms'),
	(7, 'Jaws score', 'John Williams', 'Nicholas Hersh', 'Jaws in Concert'),
	(8, 'Herald, Holler and Hallelujah', 'Wynton Marsalis', 'Xian Zhang', 'Yo-Yo Ma with New Jersey Symphony'),
	(9, 'Cello Concerto', 'Antonin Dvořák', 'Xian Zhang', 'Yo-Yo Ma with New Jersey Symphony'),
	(10, 'Selections from Four Dances from Estancia', 'Alberto Ginastera', 'Xian Zhang', 'Yo-Yo Ma with New Jersey Symphony'),
	(11, 'Symphony No. 38: Prague', 'Wolfgang Amadeus Mozart', 'George Manahan', 'Jessie Montgomery & Mozart'),
	(12, 'Rounds for Piano and String Orchestra', 'Jessie Montgomery', 'George Manahan', 'Jessie Montgomery & Mozart'),
	(13, 'Suite from Le Bourgeois Gentilhomme', 'Richard Strauss', 'George Manahan', 'Jessie Montgomery & Mozart'),
	(14, 'Egmont Overture', 'Ludwig Von Beethoven', 'Hugh Wolff', 'Hugh Wolff Conducts Beethoven & Mozart'),
	(15, 'Piano Concerto No. 25', 'Wolfgang Amadeus Mozart', 'Hugh Wolff', 'Hugh Wolff Conducts Beethoven & Mozart'),
	(16, 'Symphony No. 2', 'Aaron Jay Kernis', 'Hugh Wolff', 'Hugh Wolff Conducts Beethoven & Mozart'),
	(17, 'La Valse', 'Maurice Ravel', 'Hugh Wolff', 'Hugh Wolff Conducts Beethoven & Mozart'),
	(18, 'The Nutcracker', 'Pyotr Ilyich Tchaikovsky', 'John Yaffé', 'New Jersey Ballets Nutcracker with New Jersey Symphony'),
	(19, 'Messiah', 'George Frideric Handel', 'Xian Zhang', 'Handels Messiah'),
	(20, 'Piano Concerto No. 2', 'Johannes Brahms', 'Xian Zhang', 'Daniil Trifonov Performs Brahms'),
	(21, 'Don Juan', 'Richard Strauss', 'Xian Zhang', 'Daniil Trifonov Performs Brahms'),
	(22, 'Suite from Der Rosenkavalier', 'Richard Strauss', 'Xian Zhang', 'Daniil Trifonov Performs Brahms'),
	(23, 'Ballade in A Minor', 'Coleridge-Taylor', 'Xian Zhang', 'Hilary Hahn & Xian Zhang Unite!'),
	(24, 'Violin Concerto', 'Jean Sibelius', 'Xian Zhang', 'Hilary Hahn & Xian Zhang Unite!'),
	(25, 'Symphony No. 5', 'Sergei Prokofiev', 'Xian Zhang', 'Hilary Hahn & Xian Zhang Unite!'),
	(26, 'Harry Potter and the Deathly Hallows Part 2 score', 'Alexandre Desplat', 'Constantine Kitsopoulos', 'Harry Potter and the Deathly Hallows Part 2 in Concert'),
	(27, 'Harry Potter Theme', 'John Williams', 'Damon Gupton', 'The Best of John Williams'),
	(28, 'Jaws Theme', 'John Williams', 'Damon Gupton', 'The Best of John Williams'),
	(29, 'Star Wars Theme', 'John Williams', 'Damon Gupton', 'The Best of John Williams'),
	(30, 'Jurassic Park Theme', 'John Williams', 'Damon Gupton', 'The Best of John Williams'),
	(31, 'Symphony No. 3', 'Gustav Mahler', 'Xian Zhang', 'Mahler’s Symphony No. 3'),
	(32, 'Overture to The Barber of Seville', 'Gioachino Rossini', 'Xian Zhang', 'New Jersey Symphony Stars'),
	(33, 'The Well of Urd', 'Darryl Kubian', 'Xian Zhang', 'New Jersey Symphony Stars'),
	(34, 'Gran Duo Concertante', 'Giovanni Bottesini', 'Xian Zhang', 'New Jersey Symphony Stars'),
	(35, 'Selections from LArlésienne Suites Nos. 1 & 2', 'Georges Bizet', 'Xian Zhang', 'New Jersey Symphony Stars'),
	(36, 'Cantus in Memoriam Benjamin Britten', 'Arvo Pärt', 'Neeme Järvi', 'Neeme Järvi Conducts Tchaikovsky'),
	(37, 'Symphony No. 1: Afro-American', 'William Grant Still', 'Neeme Järvi', 'Neeme Järvi Conducts Tchaikovsky'),
	(38, 'Symphony No. 4', 'Pyotr Ilyich Tchaikovsky', 'Neeme Järvi', 'Neeme Järvi Conducts Tchaikovsky'),
	(39, 'Le Tombeau De Couperin', 'Maurice Ravel', 'Lionel Bringuier', 'Faurés Requiem'),
	(40, 'Lilacs', 'George T. Walker Jr.', 'Lionel Bringuier', 'Faurés Requiem'),
	(41, 'Requiem', 'Gabriel Fauré', 'Lionel Bringuier', 'Faurés Requiem'),
	(42, 'Symphony No. 25', 'Wolfgang Amadeus Mozart', 'Xian Zhang', 'Steven Mackey & Mozart'),
	(43, 'RIOT', 'Steven Mackey', 'Xian Zhang', 'Steven Mackey & Mozart'),
	(44, 'Overture to Don Giovanni', 'Wolfgang Amadeus Mozart', 'Xian Zhang', 'Steven Mackey & Mozart'),
	(45, 'Te Deum', 'Anton Bruckner', 'Xian Zhang', 'Steven Mackey & Mozart'),
	(46, 'Warp & Weft', 'Sarah Gibson', 'Gemma New', 'Symphonie Fantastique'),
	(47, 'Rhapsody on a Theme of Paganini', 'Sergei Rachmaninoff', 'Gemma New', 'Symphonie Fantastique'),
	(48, 'Symphonie Fantastique', 'Hector Berlioz', 'Gemma New', 'Symphonie Fantastique'),
	(49, 'Star Wars: The Empire Strikes Back score', 'John Williams', 'Constantine Kitsopoulos', 'Star Wars: The Empire Strikes Back in Concert'),
	(50, 'New Work', 'Chen Yi', 'Xian Zhang', 'Tchaikovskys Violin Concerto'),
	(51, 'Suite from Pulcinella', 'Igor Stravinsky', 'Xian Zhang', 'Tchaikovskys Violin Concerto'),
	(52, 'Violin Concerto', 'Pyotr Ilyich Tchaikovsky', 'Xian Zhang', 'Tchaikovskys Violin Concerto'),
	(53, 'New Work', 'Daniel Bernard Roumain', 'Xian Zhang', 'Season Finale with Joshua Bell'),
	(54, 'Violin Concerto No. 1', 'Max Bruch', 'Xian Zhang', 'Season Finale with Joshua Bell'),
	(55, 'The Rite of Spring', 'Igor Stravinsky', 'Xian Zhang', 'Season Finale with Joshua Bell');
